// Code generated by kueinit. DO NOT EDIT.
package modules

import (
	di "github.com/kuetix/container"
	"github.com/kuetix/engine/engine/defines"
	"github.com/kuetix/engine/engine/workflow"
	transitionsAudit "github.com/acme-kuetix/acme-audit/modules/audit/transitions"
)

func init() {
	di.Boot()
	di.DependencyInjection["audit"] = func(name string) {
		di.ToResolve(defines.TransitionPrefix+"audit"+"/"+"audit", func() interface{} { return workflow.ServiceTransitionMapping{ ServiceName: name, Name: "audit", Impl: transitionsAudit.NewAuditTransitions() }})
	}
}
